# Generated by Django 3.2 on 2021-04-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
