# Generated by Django 3.2 on 2021-04-27 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dados'),
        ),
    ]
