# Generated by Django 3.2 on 2021-04-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_produto_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tempo',
            field=models.TimeField(auto_now=True),
        ),
    ]
