# Generated by Django 3.2 on 2021-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_produto_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='anuncios_atuais',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dados',
            name='limite_anuncio',
            field=models.IntegerField(default=3),
        ),
    ]
