# Generated by Django 3.2 on 2021-04-28 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20210427_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dados',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='vendedor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.dados'),
        ),
    ]
