# Generated by Django 3.2 on 2021-04-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210427_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='Telefone',
            field=models.IntegerField(default=0),
        ),
    ]
