# Generated by Django 3.2 on 2021-04-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dados_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='oficial',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
