# Generated by Django 3.2 on 2021-04-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210428_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='subcatrgoria',
            field=models.CharField(default='', max_length=20),
        ),
    ]
