# Generated by Django 3.2 on 2021-04-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210429_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='subcatrgoria',
            field=models.CharField(max_length=20),
        ),
    ]
