# Generated by Django 3.2 on 2021-04-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210429_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='subcatrgoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(default='', max_length=20),
        ),
    ]
