# Generated by Django 3.2 on 2021-05-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='destaquecategoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='destaquegeral',
            field=models.IntegerField(default=0),
        ),
    ]
