# Generated by Django 3.2 on 2021-05-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagemprincipal',
            field=models.ImageField(blank=True, upload_to='media/produto/principal/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='media/produto/%Y/%m'),
        ),
    ]
