# Generated by Django 3.2 on 2021-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210504_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='media/produtos/secundaria/Y/%m'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagemprincipal',
            field=models.ImageField(blank=True, upload_to='media/produtos/principal/%Y/%m'),
        ),
    ]
